#!/usr/bin/env python

import sys

from rqt_mock_sms.mock_sms_module import MockSmsPlugin
from rqt_gui.main import Main

plugin = 'rqt_mock_sms'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin))